version: '3.1'

services:

    db:
      image: postgres
      ports:
        - '5432:5432'
      restart: always
      environment:
        POSTGRES_USER: testJPA      # Sets the PostgreSQL username
        POSTGRES_PASSWORD: testJPA   # Sets the password for the user
        POSTGRES_DB: trainingJPA  #Creates a default database with this name