spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingJPA
    username: testJPA
    password: testJPA
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

customer:
  variable:
    get: HelloWorld