server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingJPA
    username: testJPA
    password: testJPA
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: mohammed
      password: rifaii

customer:
  variable:
    get: HelloWorld

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: health,info
  info:
    env:
      enabled: true

info:
  name:
    app: first-crud
    description: first crud description
    version: 3.0.2

